export interface SongData {
  id: string
  title: string
  artist: string
  genre: string
  duration: number
  cover: string
  plays: number
  src: string
  description?: string
  website?: string
  phone?: string
  business?: string
}

export const songsData: SongData[] = [
  {
    id: "1",
    title: "Volcanic Bassline",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 83,
    cover: "/covers/volcanic-bassline.png",
    plays: 0,
    src: "/music/Bassline Inferno.mp3",
    description: "Bass so heavy it'll vibrate your fillings out.",
  },
  {
    id: "2",
    title: "Bassquake Mouth",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 109,
    cover: "/covers/bassquake-mouth.png",
    plays: 0,
    src: "/music/Bassquake Bounce.mp3",
    description: "Hustle rap for you lazy bastards.",
  },
  {
    id: "3",
    title: "Bulletproof Thoughts",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 80,
    cover: "/covers/bulletproof-thoughts.png",
    plays: 0,
    src: "/music/Bulletproof Thoughts.mp3",
    description: "Mental fortitude track. When your brain's being a little bitch.",
  },
  {
    id: "4",
    title: "Concrete Confetti",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 79,
    cover: "/covers/concrete-confetti.png",
    plays: 0,
    src: "/music/Concrete Confetti.mp3",
    description: "Bragging rights in song form. Got cocky after a big job.",
  },
  {
    id: "5",
    title: "Dust on the Keys (Cowboy on a Beat)",
    artist: "DJ PiGuy",
    genre: "Country Hip-Hop",
    duration: 116,
    cover: "/covers/dust-on-the-keys.png",
    plays: 0,
    src: "/music/Dust on the Keys.mp3",
    description: "Country-hop sad piano vibes. Yeah, I have feelings.",
  },
  {
    id: "6",
    title: "Lunchbox Dreams",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/lunchbox-dreams.png",
    plays: 0,
    src: "/music/Lunchbox Dreams.mp3",
    description: "Blue collar anthem about working hard and dreaming bigger. Brown bag life.",
  },
  {
    id: "7",
    title: "Lunchbox Dreams (Remix)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/lunchbox-dreams.png",
    plays: 0,
    src: "/music/Lunchbox Dreams Remix.mp3",
    description: "Same dreams, fresh beats. The brown bag anthem got an upgrade.",
  },
  {
    id: "8",
    title: "Preach to the Vinyl",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/preach-to-the-vinyl.png",
    plays: 0,
    src: "/music/Preach to the vinyl.mp3",
    description: "Old school hip-hop vibes. When the record speaks, you listen.",
  },
  {
    id: "9",
    title: "Mama's Crown",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/mamas-crown.png",
    plays: 0,
    src: "/music/Mama's Crown.mp3",
    description: "Tribute to the queens who raised us right. Get your tissues ready.",
  },
  {
    id: "10",
    title: "Nick and Mike: Pringle Kings",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 100,
    cover: "/covers/nick-and-mike-pringle-kings.png",
    plays: 0,
    src: "/music/Nick and Mike_ Pringle Kings.mp3",
    description: "Ode to the screen printing legends and their snack game. Once you pop...",
  },
  {
    id: "11",
    title: "Concrete Jungle Symphony",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 95,
    cover: "/covers/concrete-jungle-symphony.png",
    plays: 0,
    src: "/music/Rapid Fire Symphony.mp3",
    description: "Fast bars, no chill. Processors overclocked.",
  },
  {
    id: "12",
    title: "Wrapping Shadows",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 90,
    cover: "/covers/wrapping-shadows.png",
    plays: 0,
    src: "/music/Rapid Shadows.mp3",
    description: "Dark gritty vibes for edgy moods.",
  },
  {
    id: "13",
    title: "Screen Print Hustle",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 75,
    cover: "/covers/screen-print-hustle.png",
    plays: 0,
    src: "/music/Screen-Print-Hustle.mp3",
    description: "Screen printing anthem. Ink, screens, money.",
  },
  {
    id: "14",
    title: "Screen Printing Highland Beat",
    artist: "DJ PiGuy",
    genre: "Indie Pop",
    duration: 55,
    cover: "/covers/screen-printing-highland-beat.png",
    plays: 0,
    src: "/music/Screen-Printing-Highland-Beat.mp3",
    description: "Campy song about Mike and Nick printing. It's cute.",
  },
  {
    id: "15",
    title: "Straight Outta the Ass (Comedy Rap)",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 70,
    cover: "/covers/straight-outta-the-ass.png",
    plays: 0,
    src: "/music/Straight Outta Laughs.mp3",
    description: "Comedy rap. Stupid punchlines on purpose. Probably.",
  },
  {
    id: "16",
    title: "Midnight Ambitions",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 95,
    cover: "/covers/midnight-ambitions.png",
    plays: 0,
    src: "/music/Midnight Ambitions.mp3",
    description: "Late night reflections on the weight of chasing dreams. Piano keys hit different at 2am.",
  },
  {
    id: "17",
    title: "Weight of Dreams",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 145,
    cover: "/covers/weight-of-dreams.png",
    plays: 0,
    src: "/music/Weight of Dreams.mp3",
    description: "Boom bap storytelling about ambition vs reality. Heavy thoughts over mellow beats.",
  },
  {
    id: "18",
    title: "Rise From The Ashes",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 120,
    cover: "/covers/rise-from-the-ashes.png",
    plays: 0,
    src: "/music/Rise From The Ashes.mp3",
    description: "Hard-hitting comeback anthem. 808s shake while doubters watch you rise.",
  },
  {
    id: "19",
    title: "Unstoppable Grind",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 115,
    cover: "/covers/unstoppable-grind.png",
    plays: 0,
    src: "/music/Unstoppable Grind.mp3",
    description: "Aggressive delivery over hypnotic layers. For when you need to lock in.",
  },
  {
    id: "21",
    title: "Hammer and Hustle (Heart of Gold)",
    artist: "DJ PiGuy",
    genre: "Folk Hip-Hop",
    duration: 120,
    cover: "/covers/hammer-and-hustle.png",
    plays: 0,
    src: "/music/Hammer-and-Hustle-Heart-of-Gold.mp3",
    description: "Blue collar anthem celebrating construction workers. Calloused hands, unbroken pride.",
  },
  {
    id: "22",
    title: "Renusser's Prayer (Ode to Construction)",
    artist: "DJ PiGuy",
    genre: "Folk Hip-Hop",
    duration: 130,
    cover: "/covers/renussers-prayer.png",
    plays: 0,
    src: "/music/Renussers-Prayer-Ode-to-Construction.mp3",
    description: "Tribute to construction workers. Blistered palms and aching bones carving out spaces folks call home.",
  },
  {
    id: "23",
    title: "Sunshine Shirts (The Screen Printing Anthem)",
    artist: "DJ PiGuy",
    genre: "Indie Pop",
    duration: 107,
    cover: "/covers/sunshine-shirts.png",
    plays: 0,
    src: "/music/Sunshine-Shirts-The-Screen-Printing-Anthem.mp3",
    description: "Mike and Nick's screen printing anthem. Printing T's day and night, sunshine shirts burning bright!",
  },
  {
    id: "24",
    title: "Street Lessons (Cover)",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 81,
    cover: "/covers/street-lessons.png",
    plays: 0,
    src: "/music/Street-Lessons-Cover.mp3",
    description: "Cover of the street anthem about growing up on the streets. The corner store was the classroom, the block was the syllabus.",
  },
  {
    id: "25",
    title: "No Cap No Gown",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 80,
    cover: "/covers/no-cap-no-gown.png",
    plays: 0,
    src: "/music/No-Cap-No-Gown.mp3",
    description: "Hard-hitting track about getting your education from the streets. No diploma needed when survival is the final exam.",
  },
  {
    id: "26",
    title: "Broken Mirrors",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 96,
    cover: "/covers/broken-mirrors.png",
    plays: 0,
    src: "/music/Broken-Mirrors.mp3",
    description: "Introspective track about reflection and self-discovery through hardship. The cracks in the mirror tell the story of survival.",
  },
  {
    id: "27",
    title: "Chalk Lines",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 90,
    cover: "/covers/chalk-lines.png",
    plays: 0,
    src: "/music/Chalk-Lines.mp3",
    description: "Raw street poetry about childhood innocence lost to the pavement. Chalk lines on the sidewalk become chalk lines at crime scenes.",
  },
  {
    id: "28",
    title: "Turn Me Up",
    artist: "X-LABS",
    genre: "Electronic",
    duration: 156,
    cover: "/covers/x-labs-turn-me-up.png",
    plays: 0,
    src: "/music/X-LABS-Turn-Me-Up.mp3",
    description: "High-energy electronic track from X-LABS (irā x lāβ).",
    website: "iraxlab.com",
  },
  {
    id: "29",
    title: "AI Jam",
    artist: "AI Developers & Coding Crew",
    genre: "Reggae",
    duration: 134,
    cover: "/covers/ai-jam-reggae.png",
    plays: 0,
    src: "/music/AI-Jam-Regga.mp3",
    description: "Reggae vibes for the coding session. AI and developers jamming together.",
  },
  {
    id: "30",
    title: "Code Block Cartel",
    artist: "Underground Cyber Hackers",
    genre: "Hip-Hop",
    duration: 224,
    cover: "/covers/code-block-cartel.png",
    plays: 0,
    src: "/music/Code-Block-Cartel.mp3",
    description: "Dark cyberpunk beats for the underground coders. Hack the mainframe.",
  },
  {
    id: "31",
    title: "Street Lessons",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 91,
    cover: "/covers/street-lessons.png",
    plays: 0,
    src: "/music/street-lessons-cover.mp3",
    description: "Old school wisdom passed down. Respect, knowledge, and street smarts.",
  },
  {
    id: "32",
    title: "Shadow Coders",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 105,
    cover: "/covers/shadow-coders.png",
    plays: 0,
    src: "/music/Shadow-Coders.mp3",
    description: "Anonymous hackers in the server room. Code in the shadows.",
  },
  {
    id: "33",
    title: "Get On The List",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 174,
    cover: "/covers/get-on-the-list.png",
    plays: 0,
    src: "/music/Get-on-the-list.mp3",
    description: "VIP status only. Velvet ropes and exclusive vibes.",
  },
]

export function getSongById(id: string): SongData | undefined {
  return songsData.find(song => song.id === id)
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60)
  const secs = Math.floor(seconds % 60)
  return `${mins}:${secs.toString().padStart(2, "0")}`
}

// Helper functions to get optimized cover paths
export function getCoverThumb(cover: string): string {
  if (!cover || cover === "/placeholder.svg") return "/placeholder.svg"
  // Convert /covers/name.png to /covers/thumb/name.webp
  const baseName = cover.replace("/covers/", "").replace(".png", "")
  return `/covers/thumb/${baseName}.webp`
}

export function getCoverHero(cover: string): string {
  if (!cover || cover === "/placeholder.svg") return "/placeholder.svg"
  // Convert /covers/name.png to /covers/hero/name.webp
  const baseName = cover.replace("/covers/", "").replace(".png", "")
  return `/covers/hero/${baseName}.webp`
}
