export interface SongData {
  id: string
  title: string
  artist: string
  genre: string
  duration: number
  cover: string
  plays: number
  src: string
  description?: string
  phone?: string
  website?: string
  business?: string
}

export const songsData: SongData[] = [
  {
    id: "1",
    title: "Call Me Mrs. Sprayfoam",
    artist: "DJ FoamBot Productions",
    genre: "Jingle/Commercial",
    duration: 170,
    cover: "/covers/Mrs-sprayfoam-callme.jpg",
    plays: 12450,
    src: "/music/Call-Me-Mrs.Sprayfoam.mp3",
    description: "The official anthem for Karen, the legendary Mrs. Sprayfoam herself! Augusta and CSRA's most trusted insulation queen serving Georgia and South Carolina.",
    phone: "706-386-8821",
    website: "mrssprayfoam.com",
    business: "Premium Insulation & Coatings",
  },
  {
    id: "2",
    title: "Let It Foam",
    artist: "DJ FoamBot Productions feat. Mrs. SprayFoam",
    genre: "Parody/Pop",
    duration: 200,
    cover: "/covers/Mrs-sprayfoam-let-it-foam.jpg",
    plays: 15670,
    src: "/music/Mrs. SprayFoam Let It Foam.mp3",
    description: "Karen's second hit single! The Frozen parody that's taking the spray foam world by storm - LET IT FOAM, LET IT FOAM!",
    phone: "706-386-8821",
    business: "Premium Insulation & Coatings",
  },
  {
    id: "3",
    title: "Espuma y Calidez 2",
    artist: "DJ FoamBot Productions",
    genre: "Latin/Pop",
    duration: 245,
    cover: "/covers/Espuma y Calidez.jpg",
    plays: 8920,
    src: "/music/Espuma-Calidez-2.mp3",
    description: "Spanish-language track about foam and warmth - the sequel that slaps even harder!",
  },
  {
    id: "4",
    title: "Foam Everything",
    artist: "DJ FoamBot Productions",
    genre: "Anthem/Rock",
    duration: 100,
    cover: "/covers/Foameverything.jpg",
    plays: 9340,
    src: "/music/Foam-Everything.mp3",
    description: "An anthem for spray foam enthusiasts - if it can be foamed, FOAM IT!",
  },
  {
    id: "5",
    title: "Foam It - We Insulate You Right",
    artist: "DJ FoamBot Productions",
    genre: "Commercial/Jingle",
    duration: 100,
    cover: "/covers/Foam-it-we-insulate-you-right.jpg",
    plays: 7890,
    src: "/music/Foam-It-we-insulate-you-right.mp3",
    description: "The official anthem for Moe and the FoamIt crew in Mississauga! Toronto's trusted insulation experts serving the entire GTA since 2008.",
    phone: "416-893-8712",
    website: "foamit.ca",
    business: "FoamIt Insulation",
  },
  {
    id: "6",
    title: "Hey Diddle Diddle",
    artist: "DJ FoamBot Productions",
    genre: "Novelty/Fun",
    duration: 164,
    cover: "/covers/hey-diddle-diddle.jpg",
    plays: 11200,
    src: "/music/Hey-Diddle-Diddle.mp3",
    description: "A playful nursery rhyme remix with a sprayfoam twist!",
  },
  {
    id: "7",
    title: "OG Polyurethane Gang",
    artist: "DJ FoamBot Productions",
    genre: "Hip-Hop",
    duration: 68,
    cover: "/covers/polyurthane-gang.jpg",
    plays: 6540,
    src: "/music/OG-Polyurthane-gang.mp3",
    description: "Hardcore track for the real spray foam OGs - polyurethane pride!",
  },
  {
    id: "8",
    title: "Polyurethane Gang",
    artist: "DJ FoamBot Productions",
    genre: "Hip-Hop",
    duration: 67,
    cover: "/covers/polyurthane-gang.jpg",
    plays: 18900,
    src: "/music/Polyurethane-Gang.mp3",
    description: "Another banger for the polyurethane crew - rep your foam!",
  },
  {
    id: "9",
    title: "Comfy Life (Spanish Version)",
    artist: "DJ FoamBot Productions",
    genre: "Latin/Pop",
    duration: 245,
    cover: "/covers/Comfy Life (Spanish Version).jpg",
    plays: 14320,
    src: "/music/Spanish-ComfyLife.mp3",
    description: "La vida comoda - living that comfortable, well-insulated life en espanol!",
  },
  {
    id: "10",
    title: "Spray Foam Party (Snoop Style)",
    artist: "DJ FoamBot Productions",
    genre: "Hip-Hop/G-Funk",
    duration: 167,
    cover: "/covers/sprayfoam-party.jpg",
    plays: 10780,
    src: "/music/sprayfoam-party-with-Snoop-Dogg.mp3",
    description: "Drop it like it's hot, spray it like it's foam! West coast vibes meet insulation nation.",
  },
  {
    id: "11",
    title: "Spray Foam Tip Blues",
    artist: "DJ FoamBot Productions",
    genre: "Blues",
    duration: 96,
    cover: "/covers/spray-tip-blues.jpg",
    plays: 8650,
    src: "/music/Spray-Foam_tip_blues.mp3",
    description: "When your gun tip clogs and your day goes wrong - we've all been there. A blues tribute to the struggles of spray foam life.",
  },
  {
    id: "12",
    title: "Spray Foam Warmth",
    artist: "DJ FoamBot Productions",
    genre: "Novelty",
    duration: 116,
    cover: "/covers/spray-foam-warmth.jpg",
    plays: 13450,
    src: "/music/Spray-Foam-Warmth.mp3",
    description: "A quirky ode to the insulating power of spray foam. It humorously highlights how spray foam keeps you warm and cozy during cold weather.",
  },
  {
    id: "13",
    title: "DJ FoamBot - Radio Anthem",
    artist: "DJ FoamBot",
    genre: "Electronic",
    duration: 40,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 9200,
    src: "/music/SprayFoamRadio Intro.mp3",
    description: "The official SprayFoamRadio intro featuring heavy bass drops and DJ FoamBot in control!",
  },
  {
    id: "14",
    title: "DJ FoamBot - Broadcast From the Shadows",
    artist: "DJ FoamBot",
    genre: "Experimental Electronic",
    duration: 39,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 7500,
    src: "/music/SprayFoamRadio-Intro-1.mp3",
    description: "A distorted, experimental interlude evoking fragmented radio transmissions from the underground.",
  },
  {
    id: "15",
    title: "DJ FoamBot - The Master Plan",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 154,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 11800,
    src: "/music/SprayFoam Radio Ad foambot master plan.mp3",
    description: "DJ FoamBot reveals the master plan with catchy phrases and a driving beat. Boom for the master plan!",
  },
  {
    id: "16",
    title: "DJ FoamBot - We Own the Crown",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 38,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 6300,
    src: "/music/SprayFoam-Radio-Ad-2.mp3",
    description: "High-energy hip-hop interlude. DJ FoamBot owns the crown - 24/7 we don't slow down!",
  },
  {
    id: "17",
    title: "DJ FoamBot - Break It Down",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 41,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 5800,
    src: "/music/SprayFoam Radio Ad.mp3",
    description: "Heavy bass interlude with an upbeat rhythm. DJ FoamBot breaking it down on SprayFoamRadio!",
  },
  {
    id: "18",
    title: "DJ FoamBot - Hottest Hits",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 33,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 7100,
    src: "/music/SprayFoam Radio Ad with DJ Foam Bot.mp3",
    description: "Quick-fire interlude with fresh tracks and non-stop vibes. This is SprayFoamRadio!",
  },
  {
    id: "19",
    title: "DJ FoamBot - The Anthem",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 24,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 4500,
    src: "/music/SprayFoam Radio Ad_ DJ Foam Bot.mp3",
    description: "The shortest and hardest-hitting interlude. DJ FoamBot hyping up the airwaves!",
  },
  {
    id: "20",
    title: "Foam Guns For Hire",
    artist: "DJ FoamBot Productions feat. Foam Swag",
    genre: "Hip-Hop",
    duration: 83,
    cover: "/covers/foam-guns-for-hire.jpeg",
    plays: 8900,
    src: "/music/Foam Guns for Hire.mp3",
    description: "A hype track celebrating the screen printing hustle - part of the Foam Swag apparel line. Iowa's finest print shop!",
    website: "foamswag.com",
  },
  {
    id: "21",
    title: "DJ FoamBot - Sprayfoam Supreme",
    artist: "DJ FoamBot",
    genre: "Electronic/DJ Skit",
    duration: 152,
    cover: "/covers/DJ-Foambot.jpg",
    plays: 12300,
    src: "/music/Sprayfoam Supreme.mp3",
    description: "DJ FoamBot's signature extended interlude! The DJ declares spray foam supremacy over the airwaves.",
  },
  {
    id: "22",
    title: "Spray Foam Cowboy v1",
    artist: "DJ FoamBot Productions",
    genre: "Country",
    duration: 180,
    cover: "/covers/sprayfoam-cowboy.jpg",
    plays: 16500,
    src: "/music/sprayfoam-cowboy-v1.mp3",
    description: "A country-western spray foam track. Giddy up and insulate!",
  },
  {
    id: "23",
    title: "Spray Foam Cowboy v2",
    artist: "DJ FoamBot Productions",
    genre: "Country",
    duration: 165,
    cover: "/covers/sprayfoam-cowboy.jpg",
    plays: 14200,
    src: "/music/sprayfoam-cowboy-v2.mp3",
    description: "The sequel to Spray Foam Cowboy - more country spray foam vibes!",
  },
  {
    id: "24",
    title: "Seal It Up",
    artist: "DJ FoamBot Productions",
    genre: "Electronic",
    duration: 154,
    cover: "/covers/seal-it-up.jpg",
    plays: 9800,
    src: "/music/Seal it up.mp3",
    description: "A repetitive and catchy song about solidifying connections. The lyrics emphasize unity and commitment.",
  },
  {
    id: "25",
    title: "The Spray Foam Marksman",
    artist: "DJ FoamBot Productions feat. On the Mark Spray Foam",
    genre: "Indie Rock",
    duration: 122,
    cover: "/placeholder.svg",
    plays: 11500,
    src: "/music/The Spray Foam Marksman.mp3",
    description: "The official anthem for Mark and the On the Mark Spray Foam crew in Holiday, Florida! Over 20 years of precision spray foam insulation.",
    phone: "352-942-4593",
    website: "onthemarksprayfoam.net",
    business: "On the Mark Spray Foam Insulation LLC",
  },
  {
    id: "26",
    title: "Iso Stains (ALLSTATE Anthem)",
    artist: "DJ FoamBot Productions feat. Allstate Spray Foam",
    genre: "Commercial/Jingle",
    duration: 115,
    cover: "/covers/iso-stains-allstate.jpg",
    plays: 10200,
    src: "/music/Iso-Stains-ALLSTATE.mp3",
    description: "The official anthem for Rusty and the ALLSTATE crew in Visalia, California! Over 20 years of family-owned spray foam excellence.",
    phone: "559-739-9519",
    website: "allstatesprayfoam.com",
    business: "Allstate Spray Foam Insulation",
  },
  {
    id: "27",
    title: "Cali Foam Dreams (Allstate Sprayfoam)",
    artist: "DJ FoamBot Productions feat. Allstate Spray Foam",
    genre: "Commercial/Jingle",
    duration: 120,
    cover: "/covers/cali-foam-dreams-allstate.jpg",
    plays: 9600,
    src: "/music/Cali-Foam-Dreams-Allstate-Sprayfoam.mp3",
    description: "Another banger for Rusty and the ALLSTATE crew! California dreamin' with spray foam - from Visalia to the whole Golden State!",
    phone: "559-739-9519",
    website: "allstatesprayfoam.com",
    business: "Allstate Spray Foam Insulation",
  },
  {
    id: "28",
    title: "Foam is my fav F-word",
    artist: "DJ FoamBot Productions",
    genre: "Hip-Hop",
    duration: 92,
    cover: "/placeholder.svg",
    plays: 8400,
    src: "/music/Foam-is-my-fav-F-word.mp3",
    description: "You know what our favorite F-word is... FOAM!",
  },
]

export function getSongById(id: string): SongData | undefined {
  return songsData.find(song => song.id === id)
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60)
  const secs = Math.floor(seconds % 60)
  return `${mins}:${secs.toString().padStart(2, "0")}`
}
