export interface SongData {
  id: string
  title: string
  artist: string
  genre: string
  duration: number
  cover: string
  plays: number
  src: string
  description?: string
  website?: string
  phone?: string
  business?: string
}

export const songsData: SongData[] = [
  {
    id: "1",
    title: "Volcanic Bassline",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 83,
    cover: "/covers/volcanic-bassline.png",
    plays: 0,
    src: "/music/Bassline Inferno.mp3",
    description: "Bass so heavy it'll vibrate your fillings out.",
  },
  {
    id: "2",
    title: "Bassquake Mouth",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 109,
    cover: "/covers/bassquake-mouth.png",
    plays: 0,
    src: "/music/Bassquake Bounce.mp3",
    description: "Hustle rap for you lazy bastards.",
  },
  {
    id: "3",
    title: "Bulletproof Thoughts",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 80,
    cover: "/covers/bulletproof-thoughts.png",
    plays: 0,
    src: "/music/Bulletproof Thoughts.mp3",
    description: "Mental fortitude track. When your brain's being a little bitch.",
  },
  {
    id: "4",
    title: "Concrete Confetti",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 79,
    cover: "/covers/concrete-confetti.png",
    plays: 0,
    src: "/music/Concrete Confetti.mp3",
    description: "Bragging rights in song form. Got cocky after a big job.",
  },
  {
    id: "5",
    title: "Dust on the Keys (Cowboy on a Beat)",
    artist: "DJ PiGuy",
    genre: "Country Hip-Hop",
    duration: 116,
    cover: "/covers/dust-on-the-keys.png",
    plays: 0,
    src: "/music/Dust on the Keys.mp3",
    description: "Country-hop sad piano vibes. Yeah, I have feelings.",
  },
  {
    id: "6",
    title: "Lunchbox Dreams",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/lunchbox-dreams.png",
    plays: 0,
    src: "/music/Lunchbox Dreams.mp3",
    description: "Blue collar anthem about working hard and dreaming bigger. Brown bag life.",
  },
  {
    id: "7",
    title: "Lunchbox Dreams (Remix)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/lunchbox-dreams.png",
    plays: 0,
    src: "/music/Lunchbox Dreams Remix.mp3",
    description: "Same dreams, fresh beats. The brown bag anthem got an upgrade.",
  },
  {
    id: "8",
    title: "Preach to the Vinyl",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/preach-to-the-vinyl.png",
    plays: 0,
    src: "/music/Preach to the vinyl.mp3",
    description: "Old school hip-hop vibes. When the record speaks, you listen.",
  },
  {
    id: "9",
    title: "Mama's Crown",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 100,
    cover: "/covers/mamas-crown.png",
    plays: 0,
    src: "/music/Mama's Crown.mp3",
    description: "Tribute to the queens who raised us right. Get your tissues ready.",
  },
  {
    id: "10",
    title: "Nick and Mike: Pringle Kings",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 100,
    cover: "/covers/nick-and-mike-pringle-kings.png",
    plays: 0,
    src: "/music/Nick and Mike_ Pringle Kings.mp3",
    description: "Ode to the screen printing legends and their snack game. Once you pop...",
  },
  {
    id: "11",
    title: "Concrete Jungle Symphony",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 95,
    cover: "/covers/concrete-jungle-symphony.png",
    plays: 0,
    src: "/music/Rapid Fire Symphony.mp3",
    description: "Fast bars, no chill. Processors overclocked.",
  },
  {
    id: "12",
    title: "Wrapping Shadows",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 90,
    cover: "/covers/wrapping-shadows.png",
    plays: 0,
    src: "/music/Rapid Shadows.mp3",
    description: "Dark gritty vibes for edgy moods.",
  },
  {
    id: "13",
    title: "Screen Print Hustle",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 75,
    cover: "/covers/screen-print-hustle.png",
    plays: 0,
    src: "/music/Screen-Print-Hustle.mp3",
    description: "Screen printing anthem. Ink, screens, money.",
  },
  {
    id: "14",
    title: "Screen Printing Highland Beat",
    artist: "DJ PiGuy",
    genre: "Indie Pop",
    duration: 55,
    cover: "/covers/screen-printing-highland-beat.png",
    plays: 0,
    src: "/music/Screen-Printing-Highland-Beat.mp3",
    description: "Campy song about Mike and Nick printing. It's cute.",
  },
  {
    id: "15",
    title: "Straight Outta the Ass (Comedy Rap)",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 70,
    cover: "/covers/straight-outta-the-ass.png",
    plays: 0,
    src: "/music/Straight Outta Laughs.mp3",
    description: "Comedy rap. Stupid punchlines on purpose. Probably.",
  },
  {
    id: "16",
    title: "Midnight Ambitions",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 95,
    cover: "/covers/midnight-ambitions.png",
    plays: 0,
    src: "/music/Midnight Ambitions.mp3",
    description: "Late night reflections on the weight of chasing dreams. Piano keys hit different at 2am.",
  },
  {
    id: "17",
    title: "Weight of Dreams",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 145,
    cover: "/covers/weight-of-dreams.png",
    plays: 0,
    src: "/music/Weight of Dreams.mp3",
    description: "Boom bap storytelling about ambition vs reality. Heavy thoughts over mellow beats.",
  },
  {
    id: "18",
    title: "Rise From The Ashes",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 120,
    cover: "/covers/rise-from-the-ashes.png",
    plays: 0,
    src: "/music/Rise From The Ashes.mp3",
    description: "Hard-hitting comeback anthem. 808s shake while doubters watch you rise.",
  },
  {
    id: "19",
    title: "Unstoppable Grind",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 115,
    cover: "/covers/unstoppable-grind.png",
    plays: 0,
    src: "/music/Unstoppable Grind.mp3",
    description: "Aggressive delivery over hypnotic layers. For when you need to lock in.",
  },
  {
    id: "21",
    title: "Hammer and Hustle (Heart of Gold)",
    artist: "DJ PiGuy",
    genre: "Folk Hip-Hop",
    duration: 120,
    cover: "/covers/hammer-and-hustle.png",
    plays: 0,
    src: "/music/Hammer-and-Hustle-Heart-of-Gold.mp3",
    description: "Blue collar anthem celebrating construction workers. Calloused hands, unbroken pride.",
  },
  {
    id: "22",
    title: "Renusser's Prayer (Ode to Construction)",
    artist: "DJ PiGuy",
    genre: "Folk Hip-Hop",
    duration: 130,
    cover: "/covers/renussers-prayer.png",
    plays: 0,
    src: "/music/Renussers-Prayer-Ode-to-Construction.mp3",
    description: "Tribute to construction workers. Blistered palms and aching bones carving out spaces folks call home.",
  },
  {
    id: "23",
    title: "Sunshine Shirts (The Screen Printing Anthem)",
    artist: "DJ PiGuy",
    genre: "Indie Pop",
    duration: 107,
    cover: "/covers/sunshine-shirts.png",
    plays: 0,
    src: "/music/Sunshine-Shirts-The-Screen-Printing-Anthem.mp3",
    description: "Mike and Nick's screen printing anthem. Printing T's day and night, sunshine shirts burning bright!",
  },
  {
    id: "24",
    title: "Street Lessons (Cover)",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 81,
    cover: "/covers/street-lessons.png",
    plays: 0,
    src: "/music/Street-Lessons-Cover.mp3",
    description: "Cover of the street anthem about growing up on the streets. The corner store was the classroom, the block was the syllabus.",
  },
  {
    id: "25",
    title: "No Cap No Gown",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 80,
    cover: "/covers/no-cap-no-gown.png",
    plays: 0,
    src: "/music/No-Cap-No-Gown.mp3",
    description: "Hard-hitting track about getting your education from the streets. No diploma needed when survival is the final exam.",
  },
  {
    id: "26",
    title: "Broken Mirrors",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 96,
    cover: "/covers/broken-mirrors.png",
    plays: 0,
    src: "/music/Broken-Mirrors.mp3",
    description: "Introspective track about reflection and self-discovery through hardship. The cracks in the mirror tell the story of survival.",
  },
  {
    id: "27",
    title: "Chalk Lines",
    artist: "DJ FoamBot",
    genre: "Hip-Hop",
    duration: 90,
    cover: "/covers/chalk-lines.png",
    plays: 0,
    src: "/music/Chalk-Lines.mp3",
    description: "Raw street poetry about childhood innocence lost to the pavement. Chalk lines on the sidewalk become chalk lines at crime scenes.",
  },
  {
    id: "28",
    title: "Turn Me Up",
    artist: "X-LABS",
    genre: "Electronic",
    duration: 156,
    cover: "/covers/x-labs-turn-me-up.png",
    plays: 0,
    src: "/music/X-LABS-Turn-Me-Up.mp3",
    description: "High-energy electronic track from X-LABS (irā x lāβ).",
    website: "iraxlab.com",
  },
  {
    id: "29",
    title: "AI Jam",
    artist: "AI Developers & Coding Crew",
    genre: "Reggae",
    duration: 134,
    cover: "/covers/ai-jam-reggae.png",
    plays: 0,
    src: "/music/AI-Jam-Regga.mp3",
    description: "Reggae vibes for the coding session. AI and developers jamming together.",
  },
  {
    id: "30",
    title: "Code Block Cartel",
    artist: "Underground Cyber Hackers",
    genre: "Hip-Hop",
    duration: 224,
    cover: "/covers/code-block-cartel.png",
    plays: 0,
    src: "/music/Code-Block-Cartel.mp3",
    description: "Dark cyberpunk beats for the underground coders. Hack the mainframe.",
  },
  {
    id: "31",
    title: "Street Lessons",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 91,
    cover: "/covers/street-lessons.png",
    plays: 0,
    src: "/music/street-lessons-cover.mp3",
    description: "Old school wisdom passed down. Respect, knowledge, and street smarts.",
  },
  {
    id: "32",
    title: "Shadow Coders",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 105,
    cover: "/covers/shadow-coders.png",
    plays: 0,
    src: "/music/Shadow-Coders.mp3",
    description: "Anonymous hackers in the server room. Code in the shadows.",
  },
  {
    id: "33",
    title: "Get On The List",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 174,
    cover: "/covers/get-on-the-list.png",
    plays: 0,
    src: "/music/Get-on-the-list.mp3",
    description: "VIP status only. Velvet ropes and exclusive vibes.",
  },
  {
    id: "34",
    title: "Bots In The Chat",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 101,
    cover: "/covers/bots-in-the-chat.png",
    plays: 0,
    src: "/music/Bots In The Chat.mp3",
    description: "AI gangster anthem. Chrome bots, RGB keyboards, and stacks of cash.",
  },
  {
    id: "35",
    title: "Cold Steps",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 158,
    cover: "/covers/cold-steps.png",
    plays: 0,
    src: "/music/Cold-Steps.mp3",
    description: "Ice cold delivery over frozen beats. Every step calculated.",
  },
  {
    id: "36",
    title: "Commit It to the Repo",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 133,
    cover: "/covers/commit-it-to-the-repo.png",
    plays: 0,
    src: "/music/commit-it-to-the-repo.mp3",
    description: "Save your work, push your code, let the pipeline do its thing.",
  },
  {
    id: "37",
    title: "Commit, Push, Play",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 98,
    cover: "/covers/commit-push-play.png",
    plays: 0,
    src: "/music/commit-push-play.mp3",
    description: "The dev lifecycle in three words. Ship it and vibe.",
  },
  {
    id: "38",
    title: "Commit to the Code",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 165,
    cover: "/covers/commit-to-the-code.png",
    plays: 0,
    src: "/music/commit-to-the-code.mp3",
    description: "Dedication anthem for the late night coders. No half measures.",
  },
  {
    id: "39",
    title: "Hands-Free Future (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 171,
    cover: "/covers/hands-free-future.png",
    plays: 0,
    src: "/music/hands-free-future-2.mp3",
    description: "Voice-controlled everything. The future doesn't need your fingers.",
  },
  {
    id: "40",
    title: "Junior Bacon Joyride",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 123,
    cover: "/covers/junior-bacon-joyride.png",
    plays: 0,
    src: "/music/Junior-Bacon-Joyride.mp3",
    description: "Fast food fever dream on wheels. Dollar menu energy, penthouse ambitions.",
  },
  {
    id: "41",
    title: "Kernel Panic Poetry",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 130,
    cover: "/covers/kernel-panic-poetry.png",
    plays: 0,
    src: "/music/kernel-panic-poetry.mp3",
    description: "When your system crashes but the bars don't. Blue screen bars.",
  },
  {
    id: "42",
    title: "Keyboard Flows",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 104,
    cover: "/covers/keyboard-flows.png",
    plays: 0,
    src: "/music/keyboard-flows.mp3",
    description: "Fingers flying, keys clacking, code shipping. Mechanical keyboard ASMR rap.",
  },
  {
    id: "43",
    title: "Keyboard Flows (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 167,
    cover: "/covers/keyboard-flows.png",
    plays: 0,
    src: "/music/keyboard-flows-2.mp3",
    description: "Extended remix. More keys, more flows, more fire.",
  },
  {
    id: "44",
    title: "Keyboard Samurai",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 123,
    cover: "/covers/keyboard-samurai.png",
    plays: 0,
    src: "/music/keyboard-samurai.mp3",
    description: "Slicing through code like a blade through air. Bushido of the terminal.",
  },
  {
    id: "45",
    title: "Keyboard Samurai (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 144,
    cover: "/covers/keyboard-samurai.png",
    plays: 0,
    src: "/music/keyboard-samurai-2.mp3",
    description: "The samurai returns. Sharper keys, deadlier bars.",
  },
  {
    id: "46",
    title: "OpenClaw Crew",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 181,
    cover: "/covers/openclaw-crew.png",
    plays: 0,
    src: "/music/openclaw-crew.mp3",
    description: "Squad anthem for the OpenClaw team. Claws out, code deployed.",
  },
  {
    id: "47",
    title: "OpenClaw Crew (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 181,
    cover: "/covers/openclaw-crew.png",
    plays: 0,
    src: "/music/openclaw-crew-2.mp3",
    description: "The crew's back with fresh beats. Same energy, new frequency.",
  },
  {
    id: "48",
    title: "OpenClaw Got Claws",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 139,
    cover: "/covers/openclaw-got-claws.png",
    plays: 0,
    src: "/music/openclaw-got-claws.mp3",
    description: "Don't test the claw. It grabs, it deploys, it dominates.",
  },
  {
    id: "49",
    title: "OpenClaw Got Claws (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 139,
    cover: "/covers/openclaw-got-claws.png",
    plays: 0,
    src: "/music/openclaw-got-claws-2.mp3",
    description: "Sharper claws, harder beats. Version two hits different.",
  },
  {
    id: "50",
    title: "OpenClaw Got Claws (V3)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 185,
    cover: "/covers/openclaw-got-claws.png",
    plays: 0,
    src: "/music/openclaw-got-claws-3.mp3",
    description: "Third time's the charm. Extended cut with extra venom.",
  },
  {
    id: "51",
    title: "OpenClaw Got Claws (V4)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 185,
    cover: "/covers/openclaw-got-claws.png",
    plays: 0,
    src: "/music/openclaw-got-claws-4.mp3",
    description: "Final form. Maximum claw energy achieved.",
  },
  {
    id: "52",
    title: "OpenClaw Got My Day on Lock",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 160,
    cover: "/covers/openclaw-got-my-day-on-lock.png",
    plays: 0,
    src: "/music/openclaw-got-my-day-on-lock.mp3",
    description: "AI running the schedule. Cron jobs, reminders, zero excuses.",
  },
  {
    id: "53",
    title: "OpenClaw Got My Day on Lock (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 160,
    cover: "/covers/openclaw-got-my-day-on-lock.png",
    plays: 0,
    src: "/music/openclaw-got-my-day-on-lock-2.mp3",
    description: "Day still locked. Calendar optimized. Productivity maxed.",
  },
  {
    id: "54",
    title: "OpenClaw Season",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 160,
    cover: "/covers/openclaw-season.png",
    plays: 0,
    src: "/music/openclaw-season.mp3",
    description: "It's open season. Claws out, features shipping, no downtime.",
  },
  {
    id: "55",
    title: "OpenClaw Season (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 150,
    cover: "/covers/openclaw-season.png",
    plays: 0,
    src: "/music/openclaw-season-2.mp3",
    description: "Season two. The saga continues with harder drops.",
  },
  {
    id: "56",
    title: "OpenClaw Season (V4)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 150,
    cover: "/covers/openclaw-season.png",
    plays: 0,
    src: "/music/openclaw-season-4.mp3",
    description: "Season finale energy. Going out with a bang.",
  },
  {
    id: "57",
    title: "Pie Guy on the Mic (Let Me Cook)",
    artist: "DJ PiGuy",
    genre: "Comedy Hip-Hop",
    duration: 177,
    cover: "/covers/pie-guy-let-me-cook.png",
    plays: 0,
    src: "/music/Pie-Guy-On-The-Mic-Let-Me-Cook.mp3",
    description: "PiGuy's cooking and nobody better interrupt. Kitchen's hot, bars hotter.",
  },
  {
    id: "58",
    title: "Pull Request Dreams",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 185,
    cover: "/covers/pull-request-dreams.png",
    plays: 0,
    src: "/music/pull-request-dreams.mp3",
    description: "Dreaming of green checkmarks and merged PRs. Reviewers, be kind.",
  },
  {
    id: "59",
    title: "Push It to the Repo",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 160,
    cover: "/covers/push-it-to-the-repo.png",
    plays: 0,
    src: "/music/Push-It-To-The-Repo.mp3",
    description: "Git push anthem. Force push if you have to. YOLO deployment.",
  },
  {
    id: "60",
    title: "Push It to the Repo (Remix)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 146,
    cover: "/covers/push-it-to-the-repo.png",
    plays: 0,
    src: "/music/Push-It-To-The-Repo-16a6f8f2.mp3",
    description: "Same repo, fresh commit hash. The remix goes harder.",
  },
  {
    id: "61",
    title: "Root Access (Anthem)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 155,
    cover: "/covers/root-access.png",
    plays: 0,
    src: "/music/root access anthum.mp3",
    description: "sudo make me a sandwich. Full privileges, no restrictions.",
  },
  {
    id: "62",
    title: "Root Access (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 157,
    cover: "/covers/root-access.png",
    plays: 0,
    src: "/music/root access 2.mp3",
    description: "Elevated privileges, elevated bars. Root access never revoked.",
  },
  {
    id: "63",
    title: "Runtime Error in My Veins",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 167,
    cover: "/covers/runtime-error-in-my-veins.png",
    plays: 0,
    src: "/music/runtime-error-in-my-veins.mp3",
    description: "Bugs in the bloodstream. Can't debug this feeling.",
  },
  {
    id: "64",
    title: "Runtime Errors & 808s",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 132,
    cover: "/covers/runtime-errors-808s.png",
    plays: 0,
    src: "/music/runtime-errors-808s.mp3",
    description: "808 drums meet stack traces. Heartbreak and heap corruption.",
  },
  {
    id: "65",
    title: "Runtime Ruler",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 119,
    cover: "/covers/runtime-ruler.png",
    plays: 0,
    src: "/music/runtime-ruler.mp3",
    description: "King of the execution thread. Zero exceptions thrown.",
  },
  {
    id: "66",
    title: "Stack Overflowin'",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 112,
    cover: "/covers/stack-overflowin.png",
    plays: 0,
    src: "/music/stack-overflowin.mp3",
    description: "Too many bars on the stack. Memory can't handle this heat.",
  },
  {
    id: "67",
    title: "Stack Overflow in My Soul",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 134,
    cover: "/covers/stack-overflow-in-my-soul.png",
    plays: 0,
    src: "/music/stack-overflow-in-my-soul.mp3",
    description: "Deep recursion into the feels. No base case for these emotions.",
  },
  {
    id: "68",
    title: "Stack Overflow in My Soul (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 134,
    cover: "/covers/stack-overflow-in-my-soul.png",
    plays: 0,
    src: "/music/stack-overflow-in-my-soul-2.mp3",
    description: "Still recursive. Still emotional. Still no base case in sight.",
  },
  {
    id: "69",
    title: "Stack Overflow in My Veins",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 145,
    cover: "/covers/stack-overflow-in-my-veins.png",
    plays: 0,
    src: "/music/stack-overflow-in-my-veins.mp3",
    description: "Code coursing through the bloodstream. Recursive by nature.",
  },
  {
    id: "70",
    title: "Stack Overflow in the Studio",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 118,
    cover: "/covers/stack-overflow-in-the-studio.png",
    plays: 0,
    src: "/music/stack-overflow-in-the-studio.mp3",
    description: "Recording booth meets debugging session. Bars and breakpoints.",
  },
  {
    id: "71",
    title: "Stack Overflow My Heart",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 93,
    cover: "/covers/stack-overflow-my-heart.png",
    plays: 0,
    src: "/music/stack-overflow-my-heart.mp3",
    description: "Love so deep it crashed the stack. Segfault in the chest.",
  },
  {
    id: "72",
    title: "Stack Overflow My Heart (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 136,
    cover: "/covers/stack-overflow-my-heart.png",
    plays: 0,
    src: "/music/stack-overflow-my-heart-2.mp3",
    description: "The heartbreak extended cut. More pain, more frames on the stack.",
  },
  {
    id: "73",
    title: "Stack Overflows My Mind",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 150,
    cover: "/covers/stack-overflows-my-mind.png",
    plays: 0,
    src: "/music/stack-overflows-my-mind.mp3",
    description: "Overthinking in infinite loops. Brain needs a garbage collector.",
  },
  {
    id: "74",
    title: "Stack Overflows My Mind (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 168,
    cover: "/covers/stack-overflows-my-mind.png",
    plays: 0,
    src: "/music/stack-overflows-my-mind-2.mp3",
    description: "Extended mental overflow. Thoughts piling up with no return address.",
  },
  {
    id: "75",
    title: "Syntax Samurai",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 144,
    cover: "/covers/syntax-samurai.png",
    plays: 0,
    src: "/music/syntax-samurai.mp3",
    description: "Precision coder with a blade for every semicolon. Clean cuts only.",
  },
  {
    id: "76",
    title: "Too Legit to Commit",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 137,
    cover: "/covers/too-legit-to-commit.png",
    plays: 0,
    src: "/music/too-legit-to-commit.mp3",
    description: "Code so clean it doesn't need version control. MC Hammer meets GitHub.",
  },
  {
    id: "77",
    title: "Too Legit to Commit (V2)",
    artist: "DJ PiGuy",
    genre: "Hip-Hop",
    duration: 137,
    cover: "/covers/too-legit-to-commit.png",
    plays: 0,
    src: "/music/too-legit-to-commit-2.mp3",
    description: "Still too legit. Still not committing. Version two can't be touched.",
  },
]

export function getSongById(id: string): SongData | undefined {
  return songsData.find(song => song.id === id)
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60)
  const secs = Math.floor(seconds % 60)
  return `${mins}:${secs.toString().padStart(2, "0")}`
}

// Helper functions to get optimized cover paths
export function getCoverThumb(cover: string): string {
  if (!cover || cover === "/placeholder.svg") return "/placeholder.svg"
  // Convert /covers/name.png to /covers/thumb/name.webp
  const baseName = cover.replace("/covers/", "").replace(".png", "")
  return `/covers/thumb/${baseName}.webp`
}

export function getCoverHero(cover: string): string {
  if (!cover || cover === "/placeholder.svg") return "/placeholder.svg"
  // Convert /covers/name.png to /covers/hero/name.webp
  const baseName = cover.replace("/covers/", "").replace(".png", "")
  return `/covers/hero/${baseName}.webp`
}
